version: "3.8"

name: playnest

services:
  playnest-web:
    image: playnest-web:latest
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    container_name: playnest-web
    restart: always
    ports:
      - "${PLAYNEST_PORT:-3080}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
      - GA_PROPERTY_ID=${GA_PROPERTY_ID}
      - GA_CLIENT_EMAIL=${GA_CLIENT_EMAIL}
      - GA_PRIVATE_KEY=${GA_PRIVATE_KEY}
    networks:
      - playnest-isolated-network

networks:
  playnest-isolated-network:
    name: playnest-isolated-network
    driver: bridge
